/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpdesk;

/**
 *
 * @author Prem $
 */
public class Faq extends javax.swing.JFrame {

    /**
     * Creates new form FAQ
     */
    public Faq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setText("FAQs");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faq().setVisible(true);
                jTextArea1.setText("Student Help Desk FAQ\n" +
"\n" +
"1. Where is the Student Help Desk Located?\n" +
"The Student Help Desk is located in HCL, immediately inside the main entrance to the building.\n" +
"\n" +
"2. What is the phone number for the Student Help Desk?\n" +
"The Student Help Desk can be reached from any on-campus phone by dialing extension 4357 (HELP).  Phones located off-campus, including cell phones, will need to dial (717) 477-HELP (x4357) in order to reach the Help Desk. A Student Help Desk Support Technician will answer the call during business hours.  If you are calling in after hours, you may leave a detailed message that includes your name, Ship e-mail address, a phone number where you can be reached, and a brief description of the question or issue you have.\n" +
"\n" +
"3. What is the e-mail address for the Student Help Desk?\n" +
"The Student Help Desk can also be contacted via e-mail. The e-mail address is helpdesk@ship.edu.\n" +
"\n" +
"4. When is the Student Help Desk open?\n" +
"The Student Help Desk is open each day that the library is open. Please see our main page for current hours.\n" +
"\n" +
"5. Who is eligible to benefit from the services provided by the Student Help Desk?\n" +
"The Student Help Desk is responsible for providing technical support and troubleshooting services to all students attending Shippensburg University during the current semester who are able to present a valid student ID prior to services being provided.\n" +
"\n" +
"6. What services are provided by the Student Help Desk?\n" +
"The Student Help Desk provides technical support and troubleshooting assistance for all issues relating to:\n" +
"- Fixing network connectivity issues\n" +
"- Removal and cleanup of virus/malware infections\n" +
"- Installation of university-provided software\n" +
"- Installation and configuration of anti-virus\n" +
"- Testing and troubleshooting in-room network connections\n" +
"- Miscellaneous technical questions/issues.\n" +
"\n" +
"7. Is there anything that the Student Help Desk will not be able to help me with?\n" +
"The Student Help Desk will not be able to assist with hardware malfunctions/defects.  The Student Help Desk will evaluate the device in question and will attempt to make a determination as to whether the issue is hardware-related or software-related.  Should the issue be software-related, support will be given when possible.  However, should the issue be hardware-related, the Student Help Desk will refer the user to their device manufacturer for additional assistance.\n" +
"\n" +
"8. Is there a way for me to get reimbursed if a printer on campus does not process my job correctly?\n" +
"Yes, there is a way to be reimbursed.  You will need to fill out the Print Charge Dispute Form.  After you provide this information, your submission will be reviewed within two business days and your account will be credited if your submission is approved.  To fill out the form, click here:  Print Charge Dispute Form\n" +
"\n" +
"9. What is malware and how do I keep myself protected from a malware infection?\n" +
"Malware is the name that has been given to any malicious software that is built to cause damage to a user machine, computer network, server, etc.  This includes all virus, spyware, adware infections, etc.  A good way for a user to stay protected from a malware infection is to ensure that their system is up-to-date with all recent security patches and is running an up-to-date antivirus solution on their system. The best way for users to protect themselves against malware infections is to only visit sites that are known to be reputable and only download files where you know the source and are certain of the material included in the download.\n" +
"For additional information (including tools) regarding keeping a system protected from malware, users should visit the Student Help Desk site regarding Helpful Computer Tools.\n" +
"");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    protected static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
